import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/navigation/Navbar";
import Links from "@/components/navigation/Links";
import { setActiveTab } from "@/redux/reducers/theme";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "@/redux";
import CrossPage from "./Cross";
import MusicBoxPage from "./MusicBox";
import TagFinderPage from "./TagFinder";
import Clock from "@/components/navigation/Clock";
import DarkModeToggle from "@/components/navigation/DarkModeToggle";
import { useEffect } from "react";
import { initiateCross } from "@/redux/reducers/cross";
import { fetchInitialState } from "@/api/initiateRedux";
import { AbsoluteIconButton } from "@/components/AbsoluteIconButton";
import { faBars, faMusic } from "@fortawesome/free-solid-svg-icons";
import RelayPage from "./Relay";
import PlayerPage from "./Player";
import SettingPage from "./Setting";
import { initiateRecievers } from "@/redux/reducers/reciever";
import Game from "./Game";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const dispatch = useDispatch()

  useEffect(() => {
    const fetchData = async (initialFunc: Function, model: string) => {
      try {
        const data = await fetchInitialState(model);
        if (data !== null) {

          dispatch(initialFunc({value: data}));
        } else {
          // Handle the case when data is null, e.g., show an error message
        }
      } catch (error) {
        console.error('Error fetching initial state:', error);
        // Handle the error, e.g., show an error message
      }
    };

    fetchData(initiateCross, 'cross');
    fetchData(initiateRecievers, 'reciever');

  }, [dispatch]);

  const isDarkMode = useSelector((state: RootState) => state.theme.darkMode);
  const activeTab = useSelector((state: RootState) => state.theme.activeTab);
  
  const links = [
    { title: "خانه", href: "" },
    { title: "صلیب ها", href: "" },
    { title: "جن یاب", href: "" },
    { title: "تگ یاب", href: "" },
    { title: "گیرنده ها", href: "" },
  ];

  const tabs = [
    <Game key={0}/>,
    <CrossPage key={1}/>,
    <MusicBoxPage key={2}/>, 
    <TagFinderPage key={3}/>, 
    <RelayPage key={4}/>,
    <PlayerPage key={5}/>,
    <SettingPage key={6}/>
  ]


  const handleTab = (index: number) => {
    dispatch(setActiveTab(index));
  }

  return (
    <>
      <Head>
        <title>Conjuring</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={`${isDarkMode && "dark"}`}>
        <div className="bg-slate-100 dark:bg-slate-900 h-screen">
          <nav>
            <Navbar>
              <Clock />
              <Links items={links} />
              <DarkModeToggle />
            </Navbar>
          </nav>
          <main className={`h-[88%]`}>
            {tabs.map((tab, index) => (
              <div className={`${activeTab !== index ? 'hidden' : 'block'} h-full overflow-auto p-5`} key={index} >
                {tab}
              </div>
            ))}
            <AbsoluteIconButton onClick={() => handleTab(5)} icon={faMusic} position="left-0 bottom-0"/>
            <AbsoluteIconButton onClick={() => handleTab(6)} icon={faBars} position="right-0 bottom-0"/>
          </main>
        </div>
      </div>
    </>
  );
}
