import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navigation/Navbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Conjuring</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={``}>
        <div className='bg-slate-300 dark:bg-slate-900 h-screen'>
          <Navbar>
            
          </Navbar>

        </div>
      </main>
    </>
  )
}
