// In your Redux store folder, create a file named "themeSlice.ts"
import { addModel } from "@/api/addModel";
import { updateModel } from "@/api/updateModel";
import { createSlice } from "@reduxjs/toolkit";

export interface relayMCUInterface {
  [key: string]: String;
  _id: string;
  name: String;
  ip: String;
  counter: String;
}

interface relayState {
  relays: relayMCUInterface[];
  refresh: boolean;
}

const initialState: relayState = {
  relays: [],
  refresh: true,
};

// Create a Redux slice
const relaySlice = createSlice({
  name: "relay",
  initialState,
  reducers: {
    initiateRelay: (state, action) => {
      state.relays = action.payload.value;
    },
    setRelay: (state, action) => {
      const newState = [...state.relays];
      const index = action.payload.index;
      const id = newState[index]._id;
      newState[index] = action.payload.value;
      state.relays = newState;
      updateModel(id, action.payload.value, "relay");
    },
    setRefresh: (state, action) => {
      const newState = action.payload.value;
      state.refresh = newState;
    },
    pushRelay: (state, action) => {
      const newState = [...state.relays];
      const _id = addModel(action.payload.value, "relay");
      newState.push({ ...action.payload.value, _id: _id });
      state.relays = newState;
    },
  },
});

// Export the actions generated by createSlice
export const {
  setRelay,
  initiateRelay,
  setRefresh,
  pushRelay
} = relaySlice.actions;

// Export the reducer
export default relaySlice.reducer;
