// In your Redux store folder, create a file named "themeSlice.ts"
import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the initial state for the theme
interface ThemeState {
  darkMode: boolean;
}

const initialState: ThemeState = {
  darkMode: false, // Initial theme is light mode
};

// Create a Redux slice
const themeSlice = createSlice({
  name: 'theme',
  initialState,
  reducers: {
    // Action to toggle between dark and light mode
    toggleDarkMode: (state) => {
      state.darkMode = !state.darkMode;
    },

    // Action to set the theme mode explicitly
    setDarkMode: (state, action: PayloadAction<boolean>) => {
      state.darkMode = action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { toggleDarkMode, setDarkMode } = themeSlice.actions;

// Export the reducer
export default themeSlice.reducer;
